version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: -Xmx3G
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: ./gradlew dependencies
      
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      - run: ./gradlew test

      - run:
          name: Create jacoco report
          command: ./gradlew jacoco

      - store_artifacts:
          name: Store artifacts
          path: build/reports
          destination: artifacts

      - store_test_results:
          path: build/test-results

